Mailings.Web.API/ViewModels/MailingViewModel.cs
using System.ComponentModel.DataAnnotations;
using Mailings.Web.API.Controllers;

namespace Mailings.Web.API.ViewModels;
public class MailingViewModel
{
    [Required] public Guid Id { get; set; } = Guid.Empty;
    [Required] public MailingMailViewModel Mail { get; set; } = new MailingMailViewModel();
    [Required] public string Name { get; set; } = string.Empty;
    [Required] public List<string> To { get; set; } = new List<string>();
}

Mailings.Web.API/Components/MailingEntityViewComponent.cs
using Mailings.Web.API.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Mailings.Web.API.Components;
public sealed class MailingEntityViewComponent : ViewComponent
{
    private const int MaxSymbolsCountInToString = 75;

    public IViewComponentResult Invoke(MailingViewModel viewModel)
    {
        var toStr = string.Join(", ", viewModel.To);

        @ViewBag.FormattedSenders = toStr.Length > MaxSymbolsCountInToString ?
            toStr.Substring(0, MaxSymbolsCountInToString) + "..." :
            toStr;

        return View(viewModel);
    } 
}

Mailings.Web.API/Components/PaginationViewComponent.cs
using Mailings.Web.API.Controllers;
using Mailings.Web.API.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Mailings.Web.API.Components;
public class PaginationViewComponent : ViewComponent
{
    public const int MaxIncludedElements = 5;

    public IViewComponentResult Invoke(
        PaginationViewModel viewModel,
        string action,
        string controller)
    {
        var numList = new List<int>();

        var sideElementsCount = MaxIncludedElements / 2;
        for (int i = 0; i < MaxIncludedElements; i++)
        {
            int index = viewModel.PageIndex - sideElementsCount + i;
            if (index >= MailsController.StartPageIndex && 
                index <= viewModel.TotalPages)
            {
                numList.Add(index);
            }
        }

        ViewBag.FirstPage = MailsController.StartPageIndex;
        ViewBag.LastPage = viewModel.TotalPages;

        ViewBag.Action = action;
        ViewBag.Controller = controller;

        //numList is pagination indexes (pages which show to user in page on pagination)
        return View(numList);
    }
}

Mailings.Web.API/Controllers/MailingsController.cs
using System.Net.Mail;
using System.Security.Claims;
using IdentityModel;
using Mailings.Web.API.Filters;
using Mailings.Web.API.ViewModels;
using Mailings.Web.Services;
using Mailings.Web.Services.Exceptions;
using Mailings.Web.Shared.Dto;
using Mailings.Web.Shared.SystemConstants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Mailings.Web.API.Controllers;
[Authorize(AuthorizationPolicyConstants.BetaTest)]
public sealed class MailingsController : Controller
{
    public const int StartPageIndex = 1;

    private readonly IMailingGroupsResourceService _groupsResourceService;
    private readonly ITextMailsResourceService _textMailsResourceService;
    private readonly IHtmlMailsResourceService _htmlMailsResourceService;

    public MailingsController(
        IMailingGroupsResourceService groupsResourceService, 
        ITextMailsResourceService textMailsResourceService, 
        IHtmlMailsResourceService htmlMailsResourceService)
    {
        _groupsResourceService = groupsResourceService;
        _textMailsResourceService = textMailsResourceService;
        _htmlMailsResourceService = htmlMailsResourceService;
    }

    [HttpGet]
    public async Task<IActionResult> All([FromRoute] int? page = null)
    {
        page = page ?? StartPageIndex;

        if (page < StartPageIndex)
            return NotFound();

        var groups = await GetMailingsByUser();
        var viewMails = groups
            .Skip(((int)page - StartPageIndex) * ViewConstants.MailsCapacityPerPage)
            .Take(ViewConstants.MailsCapacityPerPage)
            .Select(dto => ConvertToViewModelAsync(dto).Result);

        if (!viewMails.Any() && page != StartPageIndex)
            return NotFound();

        int totalPages = (int)Math.Round(
            ((double)groups.Count() / ViewConstants.MailsCapacityPerPage),
            mode: MidpointRounding.ToPositiveInfinity);
        ViewBag.Pagination = new PaginationViewModel()
        {
            PageIndex = (int)page,
            TotalPages = totalPages != 0 ? totalPages : 1
        };

        return View(viewMails);
    }
    [HttpGet]
    [ServiceFilter(typeof(MailingsUserSecuredServiceFilter))]
    public async Task<IActionResult> More([FromRoute] string id)
    {
        var dto = RouteData
            .Values[
                MailingsUserSecuredServiceFilter.CheckedMailingKey] as MailingGroupDto;
        var viewModel = await ConvertToViewModelAsync(dto);

        return View(viewModel);
    }
    [HttpGet]
    [ServiceFilter(typeof(MailingsUserSecuredServiceFilter))]
    public async Task<IActionResult> Change([FromRoute]string id)
    {
        var dto = RouteData
            .Values[
                MailingsUserSecuredServiceFilter.CheckedMailingKey] as MailingGroupDto;
        var viewModel = await ConvertToViewModelAsync(dto);

        var mails = await GetUserMailsAsync();
        ViewData["Mails"] = mails;

        return View(viewModel);
    }
    [HttpGet]
    [ServiceFilter(typeof(MailingsUserSecuredServiceFilter))]
    public async Task<IActionResult> Delete([FromRoute]string id)
    {
        try
        {
            await _groupsResourceService.Delete(id);
        }
        catch (ObjectNotFoundException)
        {
            return NotFound();
        }

        return RedirectToAction(nameof(All));
    }
    [HttpGet]
    public async Task<ViewResult> Create()
    {
        var mails = await GetUserMailsAsync();
        ViewData["Mails"] = mails;

        return View(new MailingViewModel() /*{To = { "amerika@gmail.com" }}*/);
    }
    [ValidateAntiForgeryToken, HttpPost]
    public async Task<IActionResult> Create(MailingViewModel viewModel)
    {
        var mailsTask = GetUserMailsAsync();

        if (viewModel.To.Any())
        {
            foreach (var m in viewModel.To)
            { 
                if (!MailAddress.TryCreate(m, out var parsedMail))
                    ModelState.AddModelError(string.Empty,
                        $"Input \"{m}\" is not valid for a email value.");
            }
        }
        else
        {
            ModelState.AddModelError(string.Empty,
                $"Mailings is does not have any receivers. Please, add at " +
                $"least one to create mailings.");
        }

        if (!ModelState.IsValid)
        {
            ViewData["Mails"] = await mailsTask;
            return View(viewModel);
        }

        var userData = GetUserData();
        var mails = await mailsTask;
        var mail = mails
                       .FirstOrDefault(m => m.Id == viewModel.Mail.Id) ??
                   throw new InvalidOperationException(
                       "Mail is currently does not exist in system.");

        var dto = new MailingGroupDto()
        {
            MailId = Guid.Parse(mail.Id),
            MailType = mail.Type,
            Name = viewModel.Name,
            To = viewModel.To,
            UserId = userData.UserId,
            SenderPseudo = userData.Pseudo
        };

        await _groupsResourceService.Save(dto);

        return RedirectToAction(nameof(All));
    }
    [ValidateAntiForgeryToken, HttpPost]
    public async Task<IActionResult> Change(MailingViewModel viewModel)
    {
        var mailsTask = GetUserMailsAsync();

        if (viewModel.To.Any())
        {
            foreach (var m in viewModel.To)
            {
                if (!MailAddress.TryCreate(m, out var parsedMail))
                    ModelState.AddModelError(string.Empty,
                        $"Input \"{m}\" is not valid for a email value.");
            }
        }
        else
        {
            ModelState.AddModelError(string.Empty,
                $"Mailings is does not have any receivers. Please, add at " +
                $"least one to create mailings.");
        }

        if (!ModelState.IsValid)
        {
            ViewData["Mails"] = await mailsTask;
            return View(viewModel);
        }

        var userData = GetUserData();
        var mails = await mailsTask;
        var mail = mails
                       .FirstOrDefault(m => m.Id == viewModel.Mail.Id) ??
                   throw new InvalidOperationException(
                       "Mail is currently does not exist in system.");

        var dto = new MailingGroupDto()
        {
            Id = viewModel.Id,
            MailId = Guid.Parse(mail.Id),
            MailType = mail.Type,
            Name = viewModel.Name,
            To = viewModel.To,
            UserId = userData.UserId,
            SenderPseudo = userData.Pseudo
        };

        await _groupsResourceService.Update(dto);

        return RedirectToAction(nameof(All));
    }

    private UserData GetUserData()
    {
        var userClaims = (User.Identity as ClaimsIdentity)?
                         .Claims ??
                         throw new InvalidOperationException(
                             "User is not authenticated in system.");

        var userId = userClaims
            .FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?
            .Value ?? throw new InvalidOperationException(
            "User is not authenticated in system.");
        var pseudo = string.Join(" ", userClaims
                                          .Where(c => c.Type is 
                                              ClaimTypes.GivenName or 
                                              ClaimTypes.Surname)
                                          .Select(c => c.Value) ??
                                      throw new InvalidOperationException(
                                          "User is not authenticated in system."));

        return new UserData()
        {
            UserId = userId,
            Pseudo = pseudo
        };
    }

    private async Task<List<MailingMailViewModel>> GetUserMailsAsync()
    {
        var userId = (User.Identity as ClaimsIdentity)?.Claims?
            .FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?
            .Value;

        if (userId == null)
            throw new InvalidOperationException(
                "User is not logged in in system!");

        var htmlMails = await _htmlMailsResourceService
            .GetMailsByUserId(userId);
        var textMails = await _textMailsResourceService
            .GetMailsByUserId(userId);
        var mails = new List<MailingMailViewModel>();

        foreach (var htmlMail in htmlMails)
            mails.Add(ConvertMailToViewModel(
                dto: htmlMail, 
                type: MailTypeViewModel.Html));

        foreach (var textMail in textMails)
            mails.Add(ConvertMailToViewModel(
                dto: textMail, 
                type: MailTypeViewModel.Text));

        return mails;
    }
    private async Task<MailingViewModel> ConvertToViewModelAsync(MailingGroupDto dto)
        => new MailingViewModel
        {
            Id = dto.Id,
            Name = dto.Name,
            To = dto.To.ToList(),
            Mail = dto.MailType switch
            {
                "Html" => ConvertMailToViewModel(
                    dto: await _htmlMailsResourceService.GetById(dto.MailId.ToString()),
                    type: MailTypeViewModel.Html),
                "Text" => ConvertMailToViewModel(
                    dto: await _textMailsResourceService.GetById(dto.MailId.ToString()),
                    type: MailTypeViewModel.Text),
                _ => throw new InvalidOperationException("Unknown mail type")
            }
        };
    private MailingMailViewModel ConvertMailToViewModel(
        MailDto dto,
        MailTypeViewModel type)
        => new MailingMailViewModel()
        {
            Id = dto.Id.ToString(),
            Theme = dto.Theme,
            Type = type.ToString()
        };
    private async Task<IEnumerable<MailingGroupDto>> GetMailingsByUser()
    {
        var userId = (User.Identity as ClaimsIdentity)?.Claims
            .FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?

Mailings.Web.API/Controllers/SenderController.cs
using Mailings.Web.API.Filters;
using Mailings.Web.API.ViewModels;
using Mailings.Web.Services;
using Mailings.Web.Shared.Dto;
using Mailings.Web.Shared.SystemConstants;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Mailings.Web.API.Controllers;
[Authorize(AuthorizationPolicyConstants.BetaTest)]
public sealed class SenderController : Controller
{
    private readonly IMailingsSenderResourceService _senderResourceService;

    public SenderController(IMailingsSenderResourceService senderResourceService)
    {
        _senderResourceService = senderResourceService;
    }

    [HttpGet]
    [ServiceFilter(typeof(MailingsUserSecuredServiceFilter))]
    public ViewResult Settings([FromRoute]string id)
    {
        var dto = RouteData.Values[
            MailingsUserSecuredServiceFilter.CheckedMailingKey] as MailingGroupDto;

        if (dto == null)
            throw new InvalidOperationException(
                "Dto from filter cannot be null.");

        var viewModel = new MailingRequestViewModel()
        {
            Id = dto.Id,
            Name = dto.Name,
            MailType = dto.MailType,
        };
        return View(viewModel);
    }
    [HttpGet]
    public ViewResult ShowResponse([FromQuery] MailingResponseViewModel result)
    {
        string subject = "Mailing request error.";
        string to = "oleksii.havryk2004@gmail.com";
        string message = "Some unknown error with sending a request of applied " +
                         "new settings to mailing. ";
        string writeToEmailLink = $"https://mail.google.com/mail/?" +
                                  $"view=cm&" +
                                  $"fs=1&" +
                                  $"to={to}&" +
                                  $"su={subject}&" +
                                  $"body={message}&";

        ViewBag.WriteToEmailLink = writeToEmailLink;

        return View(result);
    }
    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> Send([FromForm] MailingRequestViewModel viewModel)
    {
        if (!ModelState.IsValid)
            return View(nameof(Settings));

        var request = new MailingRequestDto()
        {
            MailingId = viewModel.Id,
            SendType = viewModel.MailType
        };
        var response = await _senderResourceService.Send(request);

        var result = new MailingResponseViewModel()
        {
            Id = response.MailingId,
            IsSuccess = response.IsSuccess,
            Name = viewModel.Name
        };
        return RedirectToAction(nameof(ShowResponse), result);
    }
}

Mailings.Web.API/Views/Mailings/All.cshtml
@model IEnumerable<MailingViewModel>
@section Content
{
    <h2 class="main-text">All mailing groups in system</h2>
    <div class="action-block">
        <btn action="Create" controller="Mailings">Create</btn>
    </div>
    @if (Model.Any())
    {
        <list struct="Entity">
            @foreach (var el in Model) {
                <el class="mailing-entity">
                    @await Component.InvokeAsync("MailingEntity", el)
                </el>
            }
        </list>
    }
    else
    {
        <div class="text-block">
            <p>Currently you not create any groups.</p>
            <p>If you want to add new group in system:
                <a class="text-value-marker" asp-action="Create" asp-controller="Mailings">
                    click here
                </a>.
            </p>
        </div>
    }
    @await Component.InvokeAsync("Pagination", new
    {
        viewModel = ViewBag.Pagination,
        action = "All",
        controller = "Mailings"
    })
}

Mailings.Web.API/Views/Mailings/Change.cshtml
@model MailingViewModel
@section Content
{
    <h2 class="main-text">Change mailing</h2>
    <div asp-validation-summary="All">
    </div>
    <form method="post" enctype="multipart/form-data"
          asp-action="Change" asp-controller="Mailings">
        <div class="form-section">
            <h3 class="form-section-label">Mailing</h3>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name"/>
            </div>
        </div>
        <div class="form-section">
            <h3 class="form-section-label">Choose mail</h3>
            <div class="form-group">
                <label asp-for="Mail.Id">Mail</label>
                <select asp-for="Mail.Id"
                        asp-items="@(new SelectList(
                                       items: ViewData["Mails"] as 
                                            IEnumerable<MailingMailViewModel>, 
                                       dataValueField: nameof(MailingMailViewModel.Id),
                                       dataTextField: nameof(MailingMailViewModel.Theme)))">
                </select>
            </div>
        </div>
        @if (Model.To.Any())
        {
            <div id="ReceiversSection" class="form-section">
                @for (int i = 0; i < @Model.To.Count; i++)
                {
                    <div class="form-group">
                        <label asp-for="@Model.To[i]">Email @(i + 1)</label>
                        <input asp-for="@Model.To[i]"/>
                    </div>
                }
            </div>
        }
        <div class="buttons-section">
            <button type="button" id="AddReceiverButton" class="button">
                Add receiver
            </button>
            <button type="button" id="RemoveReceiverButton" class="button">
                Remove receiver
            </button>
            <button type="submit" class="button">Change</button>
        </div>
    </form>
}
@section Scripts
{
    <script asp-src-include="/lib/**.min.js" asp-src-exclude="**.slim.**js"></script>
    <environment names="development">
        <script asp-src-include="/js/modules/modal.js"></script>
        <script asp-src-include="/js/createGroup.js"></script>
    </environment>
    <environment names="staging, production">
        <script asp-src-include="/js/modules/modal.min.js"></script>
        <script asp-src-include="/js/createGroup.min.js"></script>
    </environment>
}

Mailings.Web.API/Views/Mailings/Create.cshtml
@model MailingViewModel
@section Content
{
    <h2 class="main-text">Create mailing</h2>
    <div asp-validation-summary="All">
    </div>
    <form method="post" enctype="multipart/form-data"
          asp-action="Create" asp-controller="Mailings">
        <div class="form-section">
            <h3 class="form-section-label">Mailing</h3>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name"/>
            </div>
        </div>
        <div class="form-section">
            <h3 class="form-section-label">Choose mail</h3>
            <div class="form-group">
                <label asp-for="Mail.Id"></label>
                <select asp-for="Mail.Id"
                        asp-items="@(new SelectList(
                                       items: ViewData["Mails"] as 
                                            IEnumerable<MailingMailViewModel>, 
                                       dataValueField: nameof(MailingMailViewModel.Id),
                                       dataTextField: nameof(MailingMailViewModel.Theme)))">
                </select>
            </div>
        </div>
        @if (Model.To.Any())
        {
            <div id="ReceiversSection" class="form-section">
                @for (int i = 0; i < @Model.To.Count; i++)
                {
                    <div class="form-group">
                        <label asp-for="@Model.To[i]">Email @(i + 1)</label>
                        <input asp-for="@Model.To[i]"/>
                    </div>
                }
            </div>
        }
        <div class="buttons-section">
            <button type="button" id="AddReceiverButton" class="button">
                Add receiver
            </button>
            <button type="button" id="RemoveReceiverButton" class="button">
                Remove receiver
            </button>
            <button type="submit" class="button">Create</button>
        </div>
    </form>
}
@section Scripts
{
    <script asp-src-include="/lib/**.min.js" asp-src-exclude="**.slim.**js"></script>
    <environment names="development">
        <script asp-src-include="/js/modules/modal.js"></script>
        <script asp-src-include="/js/createGroup.js"></script>
    </environment>
    <environment names="staging, production">
        <script asp-src-include="/js/modules/modal.min.js"></script>
        <script asp-src-include="/js/createGroup.min.js"></script>
    </environment>
}

Mailings.Web.API/Views/Mailings/More.cshtml
@model MailingViewModel
@section Content 
{
    <h2 class="main-text">@Model.Name</h2>
    <div class="action-block">
        <a class="button"
           asp-action="Delete" asp-controller="Mailings" 
           asp-route-id="@Model.Id">
            Delete
        </a>
        <a class="button"
           asp-action="Change" asp-controller="Mailings" 
           asp-route-id="@Model.Id">
            Change
        </a>
        <a class="button"
           asp-action="Settings" asp-controller="Sender" 
           asp-route-id="@Model.Id">
            Mailings settings
        </a>
    </div>
    <list struct="Block">
        <el>ID: @Model.Id</el>
        <el>Name: @Model.Name</el>
        <el>Mail ID: @Model.Mail.Id</el>
        <el>Mail type: @Model.Mail.Type</el>
        <el>Mail theme: @Model.Mail.Theme</el>
    </list>
    <list struct="Text">
        <elhead>Receivers</elhead>
        @{
            int counter = 1;
        }
        @foreach (var r in @Model.To)
        {
            <el>@(counter++). @r</el>
        }
    </list>
    <div class="action-block">
        <btn action="All" controller="Mailings">Back to Mailings</btn>
    </div>
}